AWSTemplateFormatVersion: "2010-09-09"

Description:
  Vpc con output test

Resources: 
  VpcTest:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: name
          Value: VpcOutputTest
Outputs:
  OutputVpcTest:
    Description: Output del vpc
    Value: !Ref VpcTest
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"