Resources:
  Ec2RefKeySg:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: santiagoKeyUsEast1
      ImageId: ami-0fc61db8544a617ed
      InstanceType: t2.micro
      SecurityGroupIds:
      - sg-05869347ff66b1fa5